### ISSUE TITLE
Bypassing values

### ISSUE THREAD

**Issue by AlexanderQueen** [hinnie123/csgo-load-library-bypass-injector#1]
If "value" is 0, how it bypasses it?
might be:
int old_value=0
int new_value=5
And than return with 0?

**Comment by hinnie123** [comment]
Take a look at the readme, if you set dword_4748FC to 0 it will return true in the "IsTrustedModule" function.
So just backup the old value, set dword_4748FC to 0, inject, and then restore the old value.

**Comment by eax0r** [comment]
From what I understood from IDA and after some tests, the actual bypass is done when we are restoring the old value.

I never had to change the value of `dword_474900` before.

**Comment by eax0r** [comment]
In the first place we never had to set `dword_474900` higher than `dword_4748FC` to actually bypass the LoadLibrary injection prevention system, just to write a value that is different from `dword_4748FC`.

**Comment by eax0r** [comment]
After many tests, I can confirm that this part in the README is wrong.

> If we just set dword_4748FC to 0, or set dword_474900 higher than dword_4748FC, when joining a game, you'll receive an error saying there has been done tampering with CS:GO's files.

So setting only dword_4748FC to 0, or setting dword_474900 higher than dword_4748FC, then not restoring the value will not cause any errors related to tampering with CS:GO's files.

**Comment by hinnie123** [comment]
> After many tests, I can confirm that this part in the README is wrong.
> 
> > If we just set dword_4748FC to 0, or set dword_474900 higher than dword_4748FC, when joining a game, you'll receive an error saying there has been done tampering with CS:GO's files.
> 
> So setting only dword_4748FC to 0, or setting dword_474900 higher than dword_4748FC, then **not restoring** the value will not cause any errors related to tampering with CS:GO's files.

It might've changed in the meantime. At the time of making this, which of the 2 methods you used doesn't matter, but you had to restore the values, otherwise, you'd get an error.

**Comment by eax0r** [comment]
> 
> 
> > After many tests, I can confirm that this part in the README is wrong.
> > > If we just set dword_4748FC to 0, or set dword_474900 higher than dword_4748FC, when joining a game, you'll receive an error saying there has been done tampering with CS:GO's files.
> > 
> > 
> > So setting only dword_4748FC to 0, or setting dword_474900 higher than dword_4748FC, then **not restoring** the value will not cause any errors related to tampering with CS:GO's files.
> 
> It might've changed in the meantime. At the time of making this, which of the 2 methods you used doesn't matter, but you had to restore the values, otherwise, you'd get an error.

Thank you for letting me know.
